### ISSUE TITLE
Update for use on SilverStripe 4

### ISSUE THREAD

**Issue by camfindlay** [camfindlay/silverstripe-twofactorauth#11]
Just thinking about updating this module for SS4 use. What is going to be required? 

Some items off top of my head are:

- [x] Update namespaces.
- [x] Update code to PSR-2 compliance.
- [x] Check for any conflicting class names/reserved names.
- [x] Write tests and test against php 5.6 and php7.
- [x] Restructure folders (seems to be a move to 'src' vs 'code' folder - up for debate though).
- [x] Improved user docs
- [x] A way for users of past 2fa module and SS3 to migrate to SS4 and new 2fa module version

Anything else?

**Comment by camfindlay** [comment]
This module standard guide updated for SS4 might provide some help https://docs.silverstripe.org/en/4/developer_guides/extending/modules/#module-standard

**Comment by camfindlay** [comment]
Adding some further useful tools we might try for this 

https://github.com/silverstripe/silverstripe-upgrader

https://gist.github.com/robbieaverill/cad0260414226645b404c45b2059fdf9

https://github.com/robbieaverill/meetup-demo

**Comment by oddnoc** [comment]
I'll take a first crack at it.

**Comment by camfindlay** [comment]
Nice one @oddnoc ! Happy to test and peer review. Could also be a good time to refactor a few things too if we make this a major release.

**Comment by oddnoc** [comment]
I've got some work in progress at https://github.com/Quinn-Interactive/silverstripe-twofactorauth/tree/ss4

Questions:

1. Should the namespace get a proper vendor prefix? If so, what should it be?
2. Do you have anything specific in mind that needs refactoring?

Thanks!

**Comment by camfindlay** [comment]
I haven't seen an official line on how we should be namespacing community modules however the other silverstripe supported modules follow a `SilverStripe\NAMEOFMODULE\` pattern we could adopt.

`SilverStripe\TwoFactorAuth\...`

Nothing off top of head to refactor for now however some tests wouldn't go a miss.

**Comment by micschk** [comment]
@oddnoc Just a heads-up on some refactoring & other enhancements on their way to master/2.1, see PR #23.

**Comment by elliot-sawyer** [comment]
I'll have some time from 19 January 2018 to help with this

**Comment by camfindlay** [comment]
@elliot-sawyer sounds good

**Comment by stephenmcm** [comment]
Hi everyone,

Resurrecting this discussion and putting forward what I've developed as an SS4 path.
Repository: https://github.com/stephenmcm/silverstripe-twofactorauth/tree/feature-ss4
Monster WIP PR: #31 

There's some drastic changes made to the codebase, but I've retained the CMS Profile and the validated flow behavior.

Design-wise the authentication and log in handling has all been moved into the Authenticator, the member extension should only be storing the members two factor configuration.

The checklists in #25 and here are partially complete:
- [x] Remove this class https://github.com/camfindlay/silverstripe-twofactorauth/blob/master/code/migration/BackupToken.php#L11
- [x] Make the new validated flow the default behaviour and clean any code we no longer need to maintain
- [x] Update code to PSR-2 compliance.
- [x] Check for any conflicting class names/reserved names.
- [x] Restructure folders (seems to be a move to 'src' vs 'code' folder - up for debate though).
 
The validated activation is now the only way of enabling two factor authentication, the non-validated flow introduces too many chances for users to lock themselves out.

As I was targeting a new build SilverStripe 4 site for these changes, compatibility with 3 wasn't considered in much detail. Tables name wise I've stuck with the same names as currently used which should make creating an upgrade path easier.

### Incomplete changes

- [ ] Release this as a major 3.0.0 version
- [ ] Freeze on this feature set for a while to help make the move to SS4.0.0 compatibility manageables
- [ ] partial - Update namespaces.
- [ ] Write tests and test against php 5.6 and php7.
- [ ] Improved user docs
- [ ] A way for users of past 2fa module and SS3 to migrate to SS4 and new 2fa module version

### Additional Feature

Enabling and enforcing 2FA is now more complex with the ability to require users in certain groups to have 2FA enabled. To support this 2FA can now be set up on the frontend, which side steps the locking a user out with no ability to turn on 2FA.

There's also an in-progress branch for replacing "[rych/otp](https://github.com/rchouinard/rych-otp)" which is mostly in-active with "[spomky-labs/otphp](https://github.com/Spomky-Labs/otphp)" which appears to be the currently favoured implementation by the php community at large.

**Comment by elliot-sawyer** [comment]
Additionally, I've got this if you need a reference. It currently works on SS4: https://github.com/elliot-sawyer/totp-authenticator

**Comment by stephenmcm** [comment]
Hey @elliot-sawyer if I recall correctly some of the name spacing is off in your module for 4.2 up. I did give it a slight test spin and decided integrating the UX/UI from this module was going to be a greater effort than bring this one up to 4.2. I'd also started on the upgrade before finding it :)

Overall I can see a future where Firesphere's MFABootstrap is the base for a TOTP module using the UX base of this module, but (big) baby steps first.

**Comment by camfindlay** [comment]
3.0.0 with SS4 compat now exists.
