### ISSUE TITLE
Userguide docs need an update

### ISSUE THREAD

**Issue by camfindlay** [camfindlay/silverstripe-twofactorauth#15]
See https://github.com/camfindlay/silverstripe-twofactorauth/blob/master/docs/en/userguide.md

Needs a few new screenshots and user docs around the new way backup codes are generated etc

**Comment by camfindlay** [comment]
Keen to get this cleaned up before we tag a next minor point release, any helpers? Should be a few screenshots and some markdown doc writing... easy peesy.

**Comment by micschk** [comment]
Working on this right now, new screenshots:
<img width="885" alt="2fa-inactive" src="https://user-images.githubusercontent.com/1005986/27372083-9e2e2f98-5663-11e7-84b4-466e6d05a937.png">
<img width="879" alt="2fa-active" src="https://user-images.githubusercontent.com/1005986/27372086-a0dfa7c6-5663-11e7-92e0-61e52562e49e.png">
<img width="883" alt="2fa-qr-backupcodes" src="https://user-images.githubusercontent.com/1005986/27372088-a2fe7b2c-5663-11e7-9fa1-d3f34560c9c5.png">
<img width="515" alt="screen shot 2017-06-21 at 09 26 54" src="https://user-images.githubusercontent.com/1005986/27372138-d0252646-5663-11e7-8e6f-a98390eec7e8.png">
![2fa-login](https://user-images.githubusercontent.com/1005986/27372473-1bb53d02-5665-11e7-8c59-224d6800b1da.png)

**Comment by camfindlay** [comment]
Thanks for this @micschk :)
