### ISSUE TITLE
A 3.0.0 major release proposal

### ISSUE THREAD

**Issue by camfindlay** [camfindlay/silverstripe-twofactorauth#25]
Propose we:
- [x] Remove this class https://github.com/camfindlay/silverstripe-twofactorauth/blob/master/code/migration/BackupToken.php#L11
- [x] Make the new validated flow the default behaviour and clean any code we no longer need to maintain
- [x] Release this as a major 3.0.0 version
- [x] Freeze on this feature set for a while to help make the move to SS4.0.0 compatibility manageable

Keen to hear your thoughts @oddnoc @micschk @Althegreat24

**Comment by micschk** [comment]
Agree on all points!
Would probably be good for the 3.0 release to include tests as this may aid in the 4.0 move? 
(Unless these tests would have to be rewritten as well, then we'd better just add them in the 4.0 branch?)

**Comment by camfindlay** [comment]
Version 3.0.0. is now tagged and released.
