### ISSUE TITLE
Issue with the install 

### ISSUE THREAD

**Issue by mandy-kate** [camfindlay/silverstripe-twofactorauth#26]
Installing with "composer require camfindlay/silverstripe-twofactorauth" gets the following error

"Package endroid/qrcode is abandoned, you should avoid using it. Use endroid/qr-code instead"

**Comment by camfindlay** [comment]
Yes, looks like they have renamed the package (also has a number of new versions which we can look into later, we'll keep 1.3.x for now).

**Comment by camfindlay** [comment]
Fixed
