### ISSUE TITLE
Create a branch for the SilverStripe3.x compatible version

### ISSUE THREAD

**Issue by camfindlay** [camfindlay/silverstripe-twofactorauth#32]
Take current master and make a branch called "2" for the 2.x.x version of this module (SilverStripe 3.x compatible).

That way when the SilverStripe 4.x compatible version is merged to master those needing bug fixes/ss3.x compat version have a workable branch.

Away from dev machine current;y, otherwise it's action now :)

CC/ @oddnoc

**Comment by oddnoc** [comment]
I've pushed branch 2 at master (014911e)

**Comment by wilr** [comment]
`2.1.1` tagged, master aliased to `3` and as @oddnoc says, `2` now exists :)
